from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
import types
from typing import Annotated, Any, Literal, Union, get_args, get_origin
from uuid import UUID
from datetime import date, datetime

from pydantic import BaseModel

from app.contracts import FRONTEND_CONTRACT_MODELS, frontend_contract_bundle
from app.schemas import WidgetActionId, WidgetType


ROOT = Path(__file__).resolve().parents[2]
GENERATED = ROOT / "frontend" / "src" / "lib" / "generated"


def ts_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def ts_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Annotated:
        return ts_type(args[0])
    if origin is Literal:
        return " | ".join(ts_literal(item) for item in args)
    union_type = getattr(types, "UnionType", None)
    if origin is Union or (union_type is not None and origin is union_type):
        return " | ".join(dict.fromkeys(ts_type(item) for item in args))
    if origin in (list, tuple, set):
        return f"Array<{ts_type(args[0])}>"
    if origin is dict:
        return f"Record<{ts_type(args[0])}, {ts_type(args[1])}>"
    if annotation in (str, UUID, date, datetime):
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation in (Any, object):
        return "unknown"
    if annotation is type(None):
        return "null"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        if annotation in (WidgetType, WidgetActionId):
            return annotation.__name__
        return " | ".join(ts_literal(item.value) for item in annotation)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__
    raise TypeError(f"Unsupported contract annotation: {annotation!r}")


def render_types(bundle: dict) -> str:
    lines = [
        "/* Generated by backend/scripts/generate_frontend_contracts.py. Do not edit. */",
        f"export const contractSchemaHash = {json.dumps(bundle['schemaHash'])} as const;",
        f"export const contractLimits = {json.dumps(bundle['limits'], ensure_ascii=False)} as const;",
    ]
    for key, type_name, lookup_name in (
        ("widgetTypes", "WidgetType", "widgetTypeIds"),
        ("widgetActions", "WidgetActionId", "widgetActionIds"),
        ("editableTransactionTypes", "EditableTransactionType", "editableTransactionTypeIds"),
    ):
        rendered = json.dumps(bundle["enums"][key], ensure_ascii=False)
        lines.extend([
            f"export const {key} = {rendered} as const;",
            f"export type {type_name} = (typeof {key})[number];",
            f"export const {lookup_name} = Object.fromEntries({key}.map((value) => [value, value])) as {{ [K in {type_name}]: K }};",
        ])
    widget_data_model_names = set(bundle["widgetDataModels"].values())
    for model in FRONTEND_CONTRACT_MODELS:
        if model.__name__ == "Widget":
            continue
        lines.append(f"export interface {model.__name__} {{")
        for name, field in model.model_fields.items():
            output_name = field.serialization_alias or field.alias or name
            optional = "?" if model.__name__ in widget_data_model_names and name in {"lifecycle", "completion"} else ""
            lines.append(f"  {output_name}{optional}: {ts_type(field.annotation)};")
        lines.append("}")
    lines.append("export interface WidgetDataByType {")
    for widget_type, model_name in bundle["widgetDataModels"].items():
        lines.append(f"  {json.dumps(widget_type)}: {model_name};")
    lines.extend([
        "}",
        "export interface Widget {",
        "  id: string;",
        "  type: keyof WidgetDataByType;",
        "  version: 1;",
        "  data: Record<string, unknown>;",
        "  actions: Array<WidgetAction>;",
        "}",
        "export type WidgetOf<K extends keyof WidgetDataByType> = Omit<Widget, \"type\" | \"data\"> & {",
        "  type: K;",
        "  data: WidgetDataByType[K];",
        "};",
    ])
    lines.append("export interface ActionPayloadById {")
    for action, model_name in bundle["actionPayloadModels"].items():
        lines.append(f"  {json.dumps(action)}: {model_name};")
    lines.extend([
        "}",
        "export type ActionPayload<A extends keyof ActionPayloadById> = ActionPayloadById[A];",
    ])
    lines.append("export interface StreamEventDataByType {")
    for event, model_name in bundle["streamEventModels"].items():
        lines.append(f"  {json.dumps(event)}: {model_name};")
    lines.extend([
        "}",
        "export type StreamEvent = {",
        "  [K in keyof StreamEventDataByType]: { event: K; data: StreamEventDataByType[K] }",
        "}[keyof StreamEventDataByType];",
    ])
    lines.extend([
        "export type Message = MessageOut;",
        "export type Bootstrap = BootstrapResponse;",
        "export type ConversationSummary = ConversationSummaryOut;",
        "export type ImportResult = ImportResultOut;",
        "",
    ])
    return "\n".join(lines)


# ── Zod emitter ──────────────────────────────────────────────────────────────
# The browser used to rebuild these schemas from the JSON document at startup,
# through `z.fromJSONSchema`. That shipped Zod's schema converter to every
# visitor — 164 KB over the wire, 47% of the initial payload — and spent about
# 39 ms of the main thread on an answer that is identical every time. The
# conversion happens here instead, once, at build time.
#
# The behaviour being reproduced is `fromJSONSchema`'s, not JSON Schema's in the
# abstract, so the output has to match it detail for detail:
#   · objects are LOOSE. Unknown keys are kept, not stripped — widget payloads
#     carry fields no schema names, and z.object() would quietly drop them.
#   · string formats are enforced: uuid, date, date-time.
#   · date-time is the strict ISO form: no offset, no fractional seconds.
#   · integers are rejected when fractional.


def zod_literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def zod_expr(node: dict, name_hint: str = "") -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[1]

    if "const" in node:
        return f"z.literal({zod_literal(node['const'])})"

    if "enum" in node:
        values = node["enum"]
        if all(isinstance(v, str) for v in values):
            return f"z.enum({json.dumps(values, ensure_ascii=False)})"
        return "z.union([" + ", ".join(f"z.literal({zod_literal(v)})" for v in values) + "])"

    if "anyOf" in node:
        return "z.union([" + ", ".join(zod_expr(item, name_hint) for item in node["anyOf"]) + "])"

    kind = node.get("type")

    if kind == "string":
        fmt = node.get("format")
        if fmt == "uuid":
            expr = "z.uuid()"
        elif fmt == "date-time":
            expr = "z.iso.datetime()"
        elif fmt == "date":
            expr = "z.iso.date()"
        elif fmt is None:
            expr = "z.string()"
        else:
            raise TypeError(f"Unsupported string format in {name_hint}: {fmt}")
        if "minLength" in node:
            expr += f".min({node['minLength']})"
        if "maxLength" in node:
            expr += f".max({node['maxLength']})"
        if "pattern" in node:
            expr += f".regex(new RegExp({json.dumps(node['pattern'])}))"
        return expr

    if kind in ("integer", "number"):
        expr = "z.int()" if kind == "integer" else "z.number()"
        if "minimum" in node:
            expr += f".min({node['minimum']})"
        if "exclusiveMinimum" in node:
            expr += f".gt({node['exclusiveMinimum']})"
        if "maximum" in node:
            expr += f".max({node['maximum']})"
        if "exclusiveMaximum" in node:
            expr += f".lt({node['exclusiveMaximum']})"
        return expr

    if kind == "boolean":
        return "z.boolean()"

    if kind == "null":
        return "z.null()"

    if kind == "array":
        items = node.get("items")
        expr = f"z.array({zod_expr(items, name_hint) if items else 'z.unknown()'})"
        if "minItems" in node:
            expr += f".min({node['minItems']})"
        if "maxItems" in node:
            expr += f".max({node['maxItems']})"
        return expr

    if kind == "object":
        properties = node.get("properties")
        if not properties:
            return "z.record(z.string(), z.unknown())"
        required = set(node.get("required", []))
        fields = []
        for key, value in properties.items():
            field = zod_expr(value, f"{name_hint}.{key}")
            if "default" in value:
                field += f".default({zod_literal(value['default'])})"
            elif key not in required:
                field += ".optional()"
            fields.append(f"  {json.dumps(key)}: {field},")
        return "z.looseObject({\n" + "\n".join(fields) + "\n})"

    if kind is None:
        return "z.unknown()"

    raise TypeError(f"Unsupported schema type in {name_hint}: {kind}")


def collect_definitions(bundle: dict) -> dict[str, dict]:
    """Every named schema in one namespace. Verified collision-free: the same
    name never carries two different bodies, so `$defs` repeated across schemas
    can be hoisted and emitted once."""
    definitions: dict[str, dict] = {}
    for name, schema in bundle["schemas"].items():
        for def_name, def_body in (schema.get("$defs") or {}).items():
            existing = definitions.get(def_name)
            if existing is not None and existing != def_body:
                raise ValueError(f"Conflicting definitions for {def_name}")
            definitions[def_name] = def_body
        definitions.setdefault(name, {k: v for k, v in schema.items() if k != "$defs"})
    return definitions


def references_of(node: Any) -> set[str]:
    found: set[str] = set()
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "$ref":
                found.add(value.rsplit("/", 1)[1])
            else:
                found |= references_of(value)
    elif isinstance(node, list):
        for item in node:
            found |= references_of(item)
    return found


def render_zod(bundle: dict) -> str:
    definitions = collect_definitions(bundle)
    edges = {name: references_of(body) & definitions.keys() for name, body in definitions.items()}

    # A const cannot be used before it is declared, so the file is written in
    # dependency order. The graph is verified acyclic; a cycle would need
    # `z.lazy` and is refused here rather than emitted as broken output.
    ordered: list[str] = []
    state: dict[str, int] = {}

    def visit(name: str, trail: tuple[str, ...]) -> None:
        if state.get(name) == 2:
            return
        if state.get(name) == 1:
            raise ValueError(f"Cyclic contract reference: {' -> '.join(trail + (name,))}")
        state[name] = 1
        for dependency in sorted(edges[name]):
            visit(dependency, trail + (name,))
        state[name] = 2
        ordered.append(name)

    for name in sorted(definitions):
        visit(name, ())

    lines = [
        "/* Generated by backend/scripts/generate_frontend_contracts.py. Do not edit.",
        " *",
        " * Built at generation time so the browser never loads Zod's JSON Schema",
        " * converter. Objects are loose on purpose: that is what `z.fromJSONSchema`",
        " * produced, and stripping unknown keys would discard widget payload fields. */",
        'import { z } from "zod";',
        "",
    ]
    for name in ordered:
        lines.append(f"export const {name} = {zod_expr(definitions[name], name)};")
    lines.extend([
        "",
        "export const schemas = {",
        *[f"  {name}," for name in sorted(bundle["schemas"])],
        "} as const;",
        "",
        "/* The two lookups the protocol layer builds by hand, resolved here so the",
        " * JSON bundle itself never has to reach the browser. */",
        "export const widgetDataSchemas = {",
        *[f"  {json.dumps(widget_type)}: {model}," for widget_type, model in bundle["widgetDataModels"].items()],
        "} as const;",
        "",
        "export const actionPayloadSchemas = {",
        *[f"  {json.dumps(action)}: {model}," for action, model in bundle["actionPayloadModels"].items()],
        "} as const;",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    bundle = frontend_contract_bundle()
    GENERATED.mkdir(parents=True, exist_ok=True)
    (GENERATED / "contracts.json").write_text(
        json.dumps(bundle, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (GENERATED / "contracts.ts").write_text(render_types(bundle), encoding="utf-8")
    (GENERATED / "contracts.zod.ts").write_text(render_zod(bundle), encoding="utf-8")


if __name__ == "__main__":
    main()
