"""Create the complete fyn AI baseline schema.

Revision ID: 0001_baseline
Revises: None
Create Date: 2026-08-19 02:56:22.820662

This is a frozen schema baseline.  It deliberately spells out every table,
constraint and index instead of importing the live ORM metadata.  PostgreSQL
analyst-role grants and tenant policies are installed after the tables because
Alembic autogeneration cannot represent them.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ANALYST_ROLE = "fyn_analyst"
TENANT_ID = "NULLIF(current_setting('app.current_user_id', true), '')::uuid"

USER_TABLES = (
    "transactions", "accounts", "account_balance_snapshots",
    "investment_holdings", "investment_valuation_snapshots", "tags",
    "financial_observations", "budgets", "goals", "goal_contributions",
    "loans", "recurring_transactions", "subscriptions",
)
EXTENDED_USER_TABLES = (
    "source_records", "source_annotations", "dashboards", "dashboard_tiles",
    "entity_links", "user_traits",
)
TENANT_TABLES = USER_TABLES + EXTENDED_USER_TABLES
SCOPED_TABLES = ("categories", "subcategories", "merchants")
CHILD_TABLES = ("transaction_sources",)
BASE_GOVERNED_TABLES = USER_TABLES + SCOPED_TABLES + CHILD_TABLES
GOVERNED_TABLES = TENANT_TABLES + SCOPED_TABLES + CHILD_TABLES


def _create_analyst_policy(table: str, predicate: str) -> None:
    op.execute(f'DROP POLICY IF EXISTS analyst_tenant_isolation ON "{table}"')
    op.execute(
        f'CREATE POLICY analyst_tenant_isolation ON "{table}" '
        f"FOR SELECT TO {ANALYST_ROLE} USING ({predicate})"
    )


def _install_analyst_security() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(sa.text(
        "DO $$ BEGIN "
        f"IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '{ANALYST_ROLE}') THEN "
        f"CREATE ROLE {ANALYST_ROLE} NOLOGIN; "
        "END IF; "
        "EXCEPTION WHEN duplicate_object THEN NULL; END $$"
    ))
    op.execute(f"GRANT {ANALYST_ROLE} TO CURRENT_USER")
    op.execute(f"GRANT USAGE ON SCHEMA public TO {ANALYST_ROLE}")
    for table in GOVERNED_TABLES:
        op.execute(f'GRANT SELECT ON "{table}" TO {ANALYST_ROLE}')
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
    for table in TENANT_TABLES:
        _create_analyst_policy(table, f"user_id = {TENANT_ID}")
    for table in SCOPED_TABLES:
        _create_analyst_policy(table, f"scope = 'system' OR owner_user_id = {TENANT_ID}")
    _create_analyst_policy(
        "transaction_sources",
        "EXISTS (SELECT 1 FROM transactions parent "
        f"WHERE parent.id = transaction_sources.transaction_id AND parent.user_id = {TENANT_ID})",
    )


def _remove_analyst_security() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in GOVERNED_TABLES:
        op.execute(f'DROP POLICY IF EXISTS analyst_tenant_isolation ON "{table}"')
        op.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')
        op.execute(f'REVOKE SELECT ON "{table}" FROM {ANALYST_ROLE}')
    op.execute(f"REVOKE USAGE ON SCHEMA public FROM {ANALYST_ROLE}")
    op.execute(sa.text(
        "DO $$ BEGIN "
        f"IF EXISTS (SELECT FROM pg_roles WHERE rolname = '{ANALYST_ROLE}') THEN "
        f"REVOKE {ANALYST_ROLE} FROM CURRENT_USER; DROP ROLE {ANALYST_ROLE}; "
        "END IF; "
        "EXCEPTION WHEN dependent_objects_still_exist THEN NULL; END $$"
    ))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('accounts',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('mask', sa.String(length=12), nullable=True),
    sa.Column('balance_minor', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('analysis_tool_templates',
    sa.Column('capability_name', sa.String(length=120), nullable=False),
    sa.Column('capability_description', sa.Text(), nullable=False),
    sa.Column('capability_signature', sa.String(length=240), nullable=False),
    sa.Column('template_version', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('semantic_registry_version', sa.String(length=60), nullable=False),
    sa.Column('source_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('plan_template', sa.JSON(), nullable=False),
    sa.Column('template_hash', sa.String(length=64), nullable=False),
    sa.Column('validation_report', sa.JSON(), nullable=False),
    sa.Column('retrieval_embedding', sa.JSON(), nullable=True),
    sa.Column('retrieval_embedding_model', sa.String(length=80), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_template_discovery', 'analysis_tool_templates', ['status', 'capability_signature'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_capability_signature'), 'analysis_tool_templates', ['capability_signature'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_created_by_user_id'), 'analysis_tool_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_semantic_registry_version'), 'analysis_tool_templates', ['semantic_registry_version'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_source_manifest_hash'), 'analysis_tool_templates', ['source_manifest_hash'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_status'), 'analysis_tool_templates', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tool_templates_template_hash'), 'analysis_tool_templates', ['template_hash'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_redacted', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'system' AND owner_user_id IS NULL) OR (scope = 'user' AND owner_user_id IS NOT NULL)", name='ck_category_scope_owner'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_owner_user_id'), 'categories', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_categories_scope'), 'categories', ['scope'], unique=False)
    op.create_table('conversations',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('active_analysis_state', sa.JSON(), nullable=True),
    sa.Column('active_data_scope', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_source_user_kind', 'data_sources', ['user_id', 'kind'], unique=False)
    op.create_index(op.f('ix_data_sources_kind'), 'data_sources', ['kind'], unique=False)
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_index(op.f('ix_data_sources_user_id'), 'data_sources', ['user_id'], unique=False)
    op.create_table('financial_insights',
    sa.Column('insight_type', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recompute_key', sa.JSON(), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stale_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'insight_type', 'subject', name='uq_financial_insight_subject')
    )
    op.create_index(op.f('ix_financial_insights_insight_type'), 'financial_insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_financial_insights_user_id'), 'financial_insights', ['user_id'], unique=False)
    op.create_table('financial_observations',
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('source_account', sa.String(length=120), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_raw', sa.String(length=255), nullable=True),
    sa.Column('merchant_normalized', sa.String(length=160), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_reference', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('processing_state', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'external_transaction_id', name='uq_observation_external_transaction_id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_hash', name='uq_observation_source_hash'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_message_id', name='uq_observation_message_id')
    )
    op.create_index(op.f('ix_financial_observations_merchant_normalized'), 'financial_observations', ['merchant_normalized'], unique=False)
    op.create_index(op.f('ix_financial_observations_source_type'), 'financial_observations', ['source_type'], unique=False)
    op.create_index(op.f('ix_financial_observations_transaction_at'), 'financial_observations', ['transaction_at'], unique=False)
    op.create_index(op.f('ix_financial_observations_user_id'), 'financial_observations', ['user_id'], unique=False)
    op.create_index('ix_observation_candidates', 'financial_observations', ['user_id', 'amount_minor', 'currency', 'transaction_type', 'transaction_at'], unique=False)
    op.create_table('goals',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_minor', sa.Integer(), nullable=False),
    sa.Column('current_minor', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('imports',
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('high_confidence_records', sa.Integer(), nullable=False),
    sa.Column('review_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'file_hash', name='uq_import_file_hash')
    )
    op.create_index(op.f('ix_imports_status'), 'imports', ['status'], unique=False)
    op.create_index(op.f('ix_imports_user_id'), 'imports', ['user_id'], unique=False)
    op.create_table('merchants',
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('normalized_name', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'system' AND owner_user_id IS NULL) OR (scope = 'user' AND owner_user_id IS NOT NULL)", name='ck_merchant_scope_owner'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_canonical_name'), 'merchants', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_merchants_normalized_name'), 'merchants', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_merchants_owner_user_id'), 'merchants', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_merchants_scope'), 'merchants', ['scope'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts_remaining', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_destination'), 'otp_challenges', ['destination'], unique=False)
    op.create_index(op.f('ix_otp_challenges_expires_at'), 'otp_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_challenges_user_id'), 'otp_challenges', ['user_id'], unique=False)
    op.create_index('ix_otp_destination_window', 'otp_challenges', ['destination', 'purpose', 'created_at'], unique=False)
    op.create_table('saved_analyses',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('analysis_type', sa.String(length=60), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_analyses_user_id'), 'saved_analyses', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('normalized_name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_name', name='uq_user_tag_name')
    )
    op.create_index(op.f('ix_tags_user_id'), 'tags', ['user_id'], unique=False)
    op.create_table('user_identities',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier', name='uq_identity_provider_identifier'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_identity_user_provider')
    )
    op.create_index(op.f('ix_user_identities_provider'), 'user_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_user_identities_user_id'), 'user_identities', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('authority', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_traits',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('freshness_note', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_trait_name')
    )
    op.create_index(op.f('ix_user_traits_name'), 'user_traits', ['name'], unique=False)
    op.create_index(op.f('ix_user_traits_user_id'), 'user_traits', ['user_id'], unique=False)
    op.create_table('account_balance_snapshots',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('balance_minor', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'observed_at', 'source_type', name='uq_account_balance_observation')
    )
    op.create_index('ix_account_balance_history', 'account_balance_snapshots', ['user_id', 'observed_at', 'account_id'], unique=False)
    op.create_index(op.f('ix_account_balance_snapshots_account_id'), 'account_balance_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_balance_snapshots_observed_at'), 'account_balance_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_account_balance_snapshots_user_id'), 'account_balance_snapshots', ['user_id'], unique=False)
    op.create_table('ai_actions',
    sa.Column('action_type', sa.String(length=80), nullable=False),
    sa.Column('payload_redacted', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_conversation_id'), 'ai_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_user_id'), 'ai_actions', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    op.create_table('dashboard_tiles',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_tiles_dashboard_id'), 'dashboard_tiles', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_tiles_user_id'), 'dashboard_tiles', ['user_id'], unique=False)
    op.create_table('entity_links',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('canonical', sa.String(length=160), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'canonical', 'alias', name='uq_entity_link_alias')
    )
    op.create_index(op.f('ix_entity_links_canonical'), 'entity_links', ['canonical'], unique=False)
    op.create_index(op.f('ix_entity_links_kind'), 'entity_links', ['kind'], unique=False)
    op.create_index(op.f('ix_entity_links_source_id'), 'entity_links', ['source_id'], unique=False)
    op.create_index(op.f('ix_entity_links_user_id'), 'entity_links', ['user_id'], unique=False)
    op.create_table('import_records',
    sa.Column('import_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('observation_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['financial_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_id', 'row_number')
    )
    op.create_index(op.f('ix_import_records_import_id'), 'import_records', ['import_id'], unique=False)
    op.create_index(op.f('ix_import_records_observation_id'), 'import_records', ['observation_id'], unique=False)
    op.create_table('investment_holdings',
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=True),
    sa.Column('asset_type', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('cost_basis_minor', sa.Integer(), nullable=False),
    sa.Column('current_value_minor', sa.Integer(), nullable=False),
    sa.Column('valued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_holdings_account_id'), 'investment_holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_holdings_asset_type'), 'investment_holdings', ['asset_type'], unique=False)
    op.create_index(op.f('ix_investment_holdings_status'), 'investment_holdings', ['status'], unique=False)
    op.create_index(op.f('ix_investment_holdings_symbol'), 'investment_holdings', ['symbol'], unique=False)
    op.create_index(op.f('ix_investment_holdings_user_id'), 'investment_holdings', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('loan_type', sa.String(length=40), nullable=False),
    sa.Column('lender', sa.String(length=140), nullable=True),
    sa.Column('outstanding_principal_minor', sa.Integer(), nullable=False),
    sa.Column('annual_rate_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('remaining_tenure_months', sa.Integer(), nullable=False),
    sa.Column('current_emi_minor', sa.Integer(), nullable=True),
    sa.Column('prepayment_fee_percent', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_account_id'), 'loans', ['account_id'], unique=False)
    op.create_index(op.f('ix_loans_status'), 'loans', ['status'], unique=False)
    op.create_index(op.f('ix_loans_user_id'), 'loans', ['user_id'], unique=False)
    op.create_table('merchant_aliases',
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('raw_alias', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('context', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_aliases_merchant_id'), 'merchant_aliases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_aliases_normalized_alias'), 'merchant_aliases', ['normalized_alias'], unique=False)
    op.create_table('messages',
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('recurring_transactions',
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('expected_amount_minor', sa.Integer(), nullable=False),
    sa.Column('cadence', sa.String(length=30), nullable=False),
    sa.Column('next_expected_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_transactions_merchant_id'), 'recurring_transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_next_expected_date'), 'recurring_transactions', ['next_expected_date'], unique=False)
    op.create_index(op.f('ix_recurring_transactions_user_id'), 'recurring_transactions', ['user_id'], unique=False)
    op.create_table('source_annotations',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'field', name='uq_source_annotation_field')
    )
    op.create_index(op.f('ix_source_annotations_data_source_id'), 'source_annotations', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_annotations_user_id'), 'source_annotations', ['user_id'], unique=False)
    op.create_table('source_manifests',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'version', name='uq_source_manifest_version')
    )
    op.create_index('ix_source_manifest_active', 'source_manifests', ['data_source_id', 'status'], unique=False)
    op.create_index(op.f('ix_source_manifests_data_source_id'), 'source_manifests', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_manifests_manifest_hash'), 'source_manifests', ['manifest_hash'], unique=False)
    op.create_index(op.f('ix_source_manifests_status'), 'source_manifests', ['status'], unique=False)
    op.create_table('source_records',
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('record', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'row_index', name='uq_source_record_row')
    )
    op.create_index(op.f('ix_source_records_data_source_id'), 'source_records', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_source_records_user_id'), 'source_records', ['user_id'], unique=False)
    op.create_table('subcategories',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'system' AND owner_user_id IS NULL) OR (scope = 'user' AND owner_user_id IS NOT NULL)", name='ck_subcategory_scope_owner'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'slug')
    )
    op.create_index(op.f('ix_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.create_index(op.f('ix_subcategories_owner_user_id'), 'subcategories', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_subcategories_scope'), 'subcategories', ['scope'], unique=False)
    op.create_table('user_analysis_tools',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('intent_signature', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['analysis_tool_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_user_analysis_tool_template')
    )
    op.create_index('ix_user_analysis_tool_discovery', 'user_analysis_tools', ['user_id', 'status', 'intent_signature'], unique=False)
    op.create_index(op.f('ix_user_analysis_tools_intent_signature'), 'user_analysis_tools', ['intent_signature'], unique=False)
    op.create_index(op.f('ix_user_analysis_tools_status'), 'user_analysis_tools', ['status'], unique=False)
    op.create_index(op.f('ix_user_analysis_tools_template_id'), 'user_analysis_tools', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_analysis_tools_user_id'), 'user_analysis_tools', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('parent_run_id', sa.Uuid(), nullable=True),
    sa.Column('blocked_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('client_message_id', sa.String(length=120), nullable=True),
    sa.Column('final_message_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('task_status', sa.String(length=24), nullable=False),
    sa.Column('failure_stage', sa.String(length=80), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('delivery_mode', sa.String(length=32), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('recovery_phase', sa.String(length=40), nullable=True),
    sa.Column('recovery_payload', sa.JSON(), nullable=False),
    sa.Column('recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('recovery_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_message_id', name='uq_agent_run_user_client_message')
    )
    op.create_index('ix_agent_run_recovery_queue', 'agent_runs', ['status', 'created_at', 'id', 'recovery_claimed_at'], unique=False)
    op.create_index('ix_agent_run_thread_status_created', 'agent_runs', ['conversation_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_blocked_by_run_id'), 'agent_runs', ['blocked_by_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_client_message_id'), 'agent_runs', ['client_message_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_final_message_id'), 'agent_runs', ['final_message_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_parent_run_id'), 'agent_runs', ['parent_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_recovery_claimed_at'), 'agent_runs', ['recovery_claimed_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_recovery_phase'), 'agent_runs', ['recovery_phase'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_status'), 'agent_runs', ['task_status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('analysis_tool_runs',
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('user_tool_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('question_hash', sa.String(length=64), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('display_names', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['analysis_tool_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_tool_id'], ['user_analysis_tools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_tool_run_replay', 'analysis_tool_runs', ['user_id', 'question_hash', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_analysis_tool_runs_conversation_id'), 'analysis_tool_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_analysis_tool_runs_status'), 'analysis_tool_runs', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tool_runs_template_id'), 'analysis_tool_runs', ['template_id'], unique=False)
    op.create_index(op.f('ix_analysis_tool_runs_user_id'), 'analysis_tool_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_analysis_tool_runs_user_tool_id'), 'analysis_tool_runs', ['user_tool_id'], unique=False)
    op.create_table('investment_valuation_snapshots',
    sa.Column('holding_id', sa.Uuid(), nullable=False),
    sa.Column('market_value_minor', sa.Integer(), nullable=False),
    sa.Column('cost_basis_minor', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['investment_holdings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_id', 'observed_at', 'source_type', name='uq_investment_valuation_observation')
    )
    op.create_index(op.f('ix_investment_valuation_snapshots_holding_id'), 'investment_valuation_snapshots', ['holding_id'], unique=False)
    op.create_index(op.f('ix_investment_valuation_snapshots_observed_at'), 'investment_valuation_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_investment_valuation_snapshots_user_id'), 'investment_valuation_snapshots', ['user_id'], unique=False)
    op.create_index('ix_investment_value_history', 'investment_valuation_snapshots', ['user_id', 'observed_at', 'holding_id'], unique=False)
    op.create_table('loan_scenarios',
    sa.Column('loan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('objective', sa.String(length=40), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_scenarios_loan_id'), 'loan_scenarios', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_scenarios_user_id'), 'loan_scenarios', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('recurring_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recurring_transaction_id'], ['recurring_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recurring_transaction_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('transaction_category_hints',
    sa.Column('merchant_pattern', sa.String(length=160), nullable=False),
    sa.Column('normalized_pattern', sa.String(length=160), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_pattern', name='uq_user_transaction_category_hint')
    )
    op.create_index(op.f('ix_transaction_category_hints_category_id'), 'transaction_category_hints', ['category_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_hints_subcategory_id'), 'transaction_category_hints', ['subcategory_id'], unique=False)
    op.create_index(op.f('ix_transaction_category_hints_user_id'), 'transaction_category_hints', ['user_id'], unique=False)
    op.create_table('transaction_drafts',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=True),
    sa.Column('merchant_name', sa.String(length=160), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('destination_account_id', sa.Uuid(), nullable=True),
    sa.Column('source_account_name', sa.String(length=120), nullable=True),
    sa.Column('destination_account_name', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_accuracy', sa.Integer(), nullable=True),
    sa.Column('location_source', sa.String(length=40), nullable=True),
    sa.Column('location_label', sa.String(length=160), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('spend_nature', sa.String(length=30), nullable=False),
    sa.Column('field_provenance', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=False),
    sa.Column('inferred_fields', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_drafts_conversation_id'), 'transaction_drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_transaction_drafts_state'), 'transaction_drafts', ['state'], unique=False)
    op.create_index(op.f('ix_transaction_drafts_transaction_at'), 'transaction_drafts', ['transaction_at'], unique=False)
    op.create_index(op.f('ix_transaction_drafts_user_id'), 'transaction_drafts', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('destination_account_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_name', sa.String(length=160), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('subcategory_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_accuracy', sa.Integer(), nullable=True),
    sa.Column('location_source', sa.String(length=40), nullable=True),
    sa.Column('location_label', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('spend_nature', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['destination_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reconciliation_window', 'transactions', ['user_id', 'account_id', 'amount_minor', 'currency', 'transaction_type', 'transaction_at'], unique=False)
    op.create_index('ix_transaction_user_at_type', 'transactions', ['user_id', 'transaction_at', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_transactions_destination_account_id'), 'transactions', ['destination_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_name'), 'transactions', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_transactions_posted_at'), 'transactions', ['posted_at'], unique=False)
    op.create_index(op.f('ix_transactions_spend_nature'), 'transactions', ['spend_nature'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_at'), 'transactions', ['transaction_at'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index('ix_transactions_user_at_category', 'transactions', ['user_id', 'transaction_at', 'category_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence', name='uq_agent_event_run_sequence')
    )
    op.create_index(op.f('ix_agent_events_event_type'), 'agent_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_events_run_id'), 'agent_events', ['run_id'], unique=False)
    op.create_table('agent_interrupts',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=120), nullable=False),
    sa.Column('widget_id', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_call_id')
    )
    op.create_index('ix_agent_interrupt_run_status', 'agent_interrupts', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_expires_at'), 'agent_interrupts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_resolved_by_run_id'), 'agent_interrupts', ['resolved_by_run_id'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_run_id'), 'agent_interrupts', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_status'), 'agent_interrupts', ['status'], unique=False)
    op.create_index(op.f('ix_agent_interrupts_widget_id'), 'agent_interrupts', ['widget_id'], unique=False)
    op.create_table('goal_contributions',
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('contribution_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_contribution_history', 'goal_contributions', ['user_id', 'goal_id', 'contribution_at'], unique=False)
    op.create_index(op.f('ix_goal_contributions_contribution_at'), 'goal_contributions', ['contribution_at'], unique=False)
    op.create_index(op.f('ix_goal_contributions_goal_id'), 'goal_contributions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_contributions_transaction_id'), 'goal_contributions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_goal_contributions_user_id'), 'goal_contributions', ['user_id'], unique=False)
    op.create_table('reconciliation_candidates',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('matching_signals', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['financial_observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_candidates_decision'), 'reconciliation_candidates', ['decision'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_observation_id'), 'reconciliation_candidates', ['observation_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_transaction_id'), 'reconciliation_candidates', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_user_id'), 'reconciliation_candidates', ['user_id'], unique=False)
    op.create_table('transaction_field_values',
    sa.Column('field_name', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=40), nullable=False),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_observation_id'], ['financial_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_field_values_field_name'), 'transaction_field_values', ['field_name'], unique=False)
    op.create_index(op.f('ix_transaction_field_values_transaction_id'), 'transaction_field_values', ['transaction_id'], unique=False)
    op.create_table('transaction_sources',
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_account', sa.String(length=120), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_reference', sa.String(length=255), nullable=True),
    sa.Column('field_values', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['financial_observations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id'),
    sa.UniqueConstraint('source_type', 'source_hash', name='uq_transaction_source_hash')
    )
    op.create_index(op.f('ix_transaction_sources_source_type'), 'transaction_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_transaction_sources_transaction_id'), 'transaction_sources', ['transaction_id'], unique=False)
    op.create_table('transaction_tags',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'tag_id', name='uq_transaction_tag')
    )
    op.create_index(op.f('ix_transaction_tags_tag_id'), 'transaction_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_transaction_tags_transaction_id'), 'transaction_tags', ['transaction_id'], unique=False)
    op.create_table('reconciliation_decisions',
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decided_by', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['reconciliation_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_decisions_candidate_id'), 'reconciliation_decisions', ['candidate_id'], unique=False)
    _install_analyst_security()
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _remove_analyst_security()
    op.drop_index(op.f('ix_reconciliation_decisions_candidate_id'), table_name='reconciliation_decisions')
    op.drop_table('reconciliation_decisions')
    op.drop_index(op.f('ix_transaction_tags_transaction_id'), table_name='transaction_tags')
    op.drop_index(op.f('ix_transaction_tags_tag_id'), table_name='transaction_tags')
    op.drop_table('transaction_tags')
    op.drop_index(op.f('ix_transaction_sources_transaction_id'), table_name='transaction_sources')
    op.drop_index(op.f('ix_transaction_sources_source_type'), table_name='transaction_sources')
    op.drop_table('transaction_sources')
    op.drop_index(op.f('ix_transaction_field_values_transaction_id'), table_name='transaction_field_values')
    op.drop_index(op.f('ix_transaction_field_values_field_name'), table_name='transaction_field_values')
    op.drop_table('transaction_field_values')
    op.drop_index(op.f('ix_reconciliation_candidates_user_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_transaction_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_observation_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_decision'), table_name='reconciliation_candidates')
    op.drop_table('reconciliation_candidates')
    op.drop_index(op.f('ix_goal_contributions_user_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_transaction_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_goal_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_contribution_at'), table_name='goal_contributions')
    op.drop_index('ix_goal_contribution_history', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index(op.f('ix_agent_interrupts_widget_id'), table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_status'), table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_run_id'), table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_resolved_by_run_id'), table_name='agent_interrupts')
    op.drop_index(op.f('ix_agent_interrupts_expires_at'), table_name='agent_interrupts')
    op.drop_index('ix_agent_interrupt_run_status', table_name='agent_interrupts')
    op.drop_table('agent_interrupts')
    op.drop_index(op.f('ix_agent_events_run_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_event_type'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_user_at_category', table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_spend_nature'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_posted_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_name'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_destination_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('ix_transaction_user_at_type', table_name='transactions')
    op.drop_index('ix_reconciliation_window', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_drafts_user_id'), table_name='transaction_drafts')
    op.drop_index(op.f('ix_transaction_drafts_transaction_at'), table_name='transaction_drafts')
    op.drop_index(op.f('ix_transaction_drafts_state'), table_name='transaction_drafts')
    op.drop_index(op.f('ix_transaction_drafts_conversation_id'), table_name='transaction_drafts')
    op.drop_table('transaction_drafts')
    op.drop_index(op.f('ix_transaction_category_hints_user_id'), table_name='transaction_category_hints')
    op.drop_index(op.f('ix_transaction_category_hints_subcategory_id'), table_name='transaction_category_hints')
    op.drop_index(op.f('ix_transaction_category_hints_category_id'), table_name='transaction_category_hints')
    op.drop_table('transaction_category_hints')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_loan_scenarios_user_id'), table_name='loan_scenarios')
    op.drop_index(op.f('ix_loan_scenarios_loan_id'), table_name='loan_scenarios')
    op.drop_table('loan_scenarios')
    op.drop_index('ix_investment_value_history', table_name='investment_valuation_snapshots')
    op.drop_index(op.f('ix_investment_valuation_snapshots_user_id'), table_name='investment_valuation_snapshots')
    op.drop_index(op.f('ix_investment_valuation_snapshots_observed_at'), table_name='investment_valuation_snapshots')
    op.drop_index(op.f('ix_investment_valuation_snapshots_holding_id'), table_name='investment_valuation_snapshots')
    op.drop_table('investment_valuation_snapshots')
    op.drop_index(op.f('ix_analysis_tool_runs_user_tool_id'), table_name='analysis_tool_runs')
    op.drop_index(op.f('ix_analysis_tool_runs_user_id'), table_name='analysis_tool_runs')
    op.drop_index(op.f('ix_analysis_tool_runs_template_id'), table_name='analysis_tool_runs')
    op.drop_index(op.f('ix_analysis_tool_runs_status'), table_name='analysis_tool_runs')
    op.drop_index(op.f('ix_analysis_tool_runs_conversation_id'), table_name='analysis_tool_runs')
    op.drop_index('ix_analysis_tool_run_replay', table_name='analysis_tool_runs')
    op.drop_table('analysis_tool_runs')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_task_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_recovery_phase'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_recovery_claimed_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_parent_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_final_message_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_client_message_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_blocked_by_run_id'), table_name='agent_runs')
    op.drop_index('ix_agent_run_thread_status_created', table_name='agent_runs')
    op.drop_index('ix_agent_run_recovery_queue', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_user_analysis_tools_user_id'), table_name='user_analysis_tools')
    op.drop_index(op.f('ix_user_analysis_tools_template_id'), table_name='user_analysis_tools')
    op.drop_index(op.f('ix_user_analysis_tools_status'), table_name='user_analysis_tools')
    op.drop_index(op.f('ix_user_analysis_tools_intent_signature'), table_name='user_analysis_tools')
    op.drop_index('ix_user_analysis_tool_discovery', table_name='user_analysis_tools')
    op.drop_table('user_analysis_tools')
    op.drop_index(op.f('ix_subcategories_scope'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_owner_user_id'), table_name='subcategories')
    op.drop_index(op.f('ix_subcategories_category_id'), table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_source_records_user_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_data_source_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_source_manifests_status'), table_name='source_manifests')
    op.drop_index(op.f('ix_source_manifests_manifest_hash'), table_name='source_manifests')
    op.drop_index(op.f('ix_source_manifests_data_source_id'), table_name='source_manifests')
    op.drop_index('ix_source_manifest_active', table_name='source_manifests')
    op.drop_table('source_manifests')
    op.drop_index(op.f('ix_source_annotations_user_id'), table_name='source_annotations')
    op.drop_index(op.f('ix_source_annotations_data_source_id'), table_name='source_annotations')
    op.drop_table('source_annotations')
    op.drop_index(op.f('ix_recurring_transactions_user_id'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_next_expected_date'), table_name='recurring_transactions')
    op.drop_index(op.f('ix_recurring_transactions_merchant_id'), table_name='recurring_transactions')
    op.drop_table('recurring_transactions')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_merchant_aliases_normalized_alias'), table_name='merchant_aliases')
    op.drop_index(op.f('ix_merchant_aliases_merchant_id'), table_name='merchant_aliases')
    op.drop_table('merchant_aliases')
    op.drop_index(op.f('ix_loans_user_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_account_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_investment_holdings_user_id'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_symbol'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_status'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_asset_type'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_account_id'), table_name='investment_holdings')
    op.drop_table('investment_holdings')
    op.drop_index(op.f('ix_import_records_observation_id'), table_name='import_records')
    op.drop_index(op.f('ix_import_records_import_id'), table_name='import_records')
    op.drop_table('import_records')
    op.drop_index(op.f('ix_entity_links_user_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_source_id'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_kind'), table_name='entity_links')
    op.drop_index(op.f('ix_entity_links_canonical'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_dashboard_tiles_user_id'), table_name='dashboard_tiles')
    op.drop_index(op.f('ix_dashboard_tiles_dashboard_id'), table_name='dashboard_tiles')
    op.drop_table('dashboard_tiles')
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_ai_actions_user_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_conversation_id'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_index(op.f('ix_account_balance_snapshots_user_id'), table_name='account_balance_snapshots')
    op.drop_index(op.f('ix_account_balance_snapshots_observed_at'), table_name='account_balance_snapshots')
    op.drop_index(op.f('ix_account_balance_snapshots_account_id'), table_name='account_balance_snapshots')
    op.drop_index('ix_account_balance_history', table_name='account_balance_snapshots')
    op.drop_table('account_balance_snapshots')
    op.drop_index(op.f('ix_user_traits_user_id'), table_name='user_traits')
    op.drop_index(op.f('ix_user_traits_name'), table_name='user_traits')
    op.drop_table('user_traits')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_identities_user_id'), table_name='user_identities')
    op.drop_index(op.f('ix_user_identities_provider'), table_name='user_identities')
    op.drop_table('user_identities')
    op.drop_index(op.f('ix_tags_user_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_saved_analyses_user_id'), table_name='saved_analyses')
    op.drop_table('saved_analyses')
    op.drop_index('ix_otp_destination_window', table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_user_id'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_expires_at'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_destination'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_merchants_scope'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_owner_user_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_normalized_name'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_canonical_name'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_imports_user_id'), table_name='imports')
    op.drop_index(op.f('ix_imports_status'), table_name='imports')
    op.drop_table('imports')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index('ix_observation_candidates', table_name='financial_observations')
    op.drop_index(op.f('ix_financial_observations_user_id'), table_name='financial_observations')
    op.drop_index(op.f('ix_financial_observations_transaction_at'), table_name='financial_observations')
    op.drop_index(op.f('ix_financial_observations_source_type'), table_name='financial_observations')
    op.drop_index(op.f('ix_financial_observations_merchant_normalized'), table_name='financial_observations')
    op.drop_table('financial_observations')
    op.drop_index(op.f('ix_financial_insights_user_id'), table_name='financial_insights')
    op.drop_index(op.f('ix_financial_insights_insight_type'), table_name='financial_insights')
    op.drop_table('financial_insights')
    op.drop_index(op.f('ix_data_sources_user_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_kind'), table_name='data_sources')
    op.drop_index('ix_data_source_user_kind', table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_dashboards_user_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_categories_scope'), table_name='categories')
    op.drop_index(op.f('ix_categories_owner_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analysis_tool_templates_template_hash'), table_name='analysis_tool_templates')
    op.drop_index(op.f('ix_analysis_tool_templates_status'), table_name='analysis_tool_templates')
    op.drop_index(op.f('ix_analysis_tool_templates_source_manifest_hash'), table_name='analysis_tool_templates')
    op.drop_index(op.f('ix_analysis_tool_templates_semantic_registry_version'), table_name='analysis_tool_templates')
    op.drop_index(op.f('ix_analysis_tool_templates_created_by_user_id'), table_name='analysis_tool_templates')
    op.drop_index(op.f('ix_analysis_tool_templates_capability_signature'), table_name='analysis_tool_templates')
    op.drop_index('ix_analysis_template_discovery', table_name='analysis_tool_templates')
    op.drop_table('analysis_tool_templates')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
